In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
import random
import tensorflow as tf
import math
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [2]:
def seed_everything(seed):
  random.seed(seed)
  os.environ['PYTHONHASHSEED'] = str(seed)
  np.random.seed(seed)
  tf.random.set_seed(seed)

SEED = 22
seed_everything(seed=SEED)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=SEED)

X_train

array([[6, 7],
       [0, 1],
       [8, 9]])

In [6]:
a, b, c, d = train_test_split(X, y, test_size=0.33, random_state=SEED)
a

array([[6, 7],
       [0, 1],
       [8, 9]])

In [5]:
AX, Ay = np.arange(10, 20).reshape((5, 2)), range(5)
AX

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [6]:
i, j, k, l = train_test_split(AX, Ay, test_size=0.33, random_state=SEED)
i

array([[16, 17],
       [10, 11],
       [18, 19]])

In [3]:
a = tf.reshape(tf.range(0.0, 16.0), [-1, 2, 4])
b = tf.reshape(tf.range(10.0, 26.0), [-1, 2, 4])
c = tf.reshape(tf.range(20.0, 36.0), [-1, 2, 4])
d = tf.reshape(tf.range(30.0, 46.0), [-1, 2, 4])

In [4]:
a

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]], dtype=float32)>

In [10]:
x = a[:, :, 0:2]

In [11]:
y = a[:, :, -1:]

In [17]:
w = tf.concat((x, y), axis=2)
w

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  3.],
        [ 4.,  5.,  7.]],

       [[ 8.,  9., 11.],
        [12., 13., 15.]]], dtype=float32)>

In [19]:
v = tf.concat((d[:, :, 0:2], d[:, :, -1:]), axis=2)
v

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[30., 31., 33.],
        [34., 35., 37.]],

       [[38., 39., 41.],
        [42., 43., 45.]]], dtype=float32)>

In [23]:
j = tf.concat((w, v), axis=0)

In [24]:
j

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  3.],
        [ 4.,  5.,  7.]],

       [[ 8.,  9., 11.],
        [12., 13., 15.]],

       [[30., 31., 33.],
        [34., 35., 37.]],

       [[38., 39., 41.],
        [42., 43., 45.]]], dtype=float32)>

In [25]:
j[:, :, :2]

<tf.Tensor: shape=(4, 2, 2), dtype=float32, numpy=
array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]],

       [[30., 31.],
        [34., 35.]],

       [[38., 39.],
        [42., 43.]]], dtype=float32)>